spring.application.name=todo-rest

# MySQL / MariaDB Connection (Usa variables si existen, si no, usa local)
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:todo_db}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configurar el puerto dinámico de Railway (Si no existe, usa el 8080)
server.port=${API_PORT:8080}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Data Initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Thymeleaf Config
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.forward-headers-strategy=native
server.use-forward-headers=true